version: "3"

services:
###################
#      BACK       #
###################

    http-back:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - /var/www/nfc/back:/var/www/back
            - /var/www/nfc/back/back.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
        links:
            - php-back:php
        networks:
            - nfc
    php-back:
        build: ./
        working_dir: /var/www/back
        volumes:
            - /var/www/nfc/back:/var/www/back
            - ~/.composer:/root/.composer
        links:
            - mysql-back:db
        networks:
            - nfc
        expose:
            - 9000
    mysql-back:
        image: mariadb:latest
        command: --sql_mode=""
        ports:
            - "8091:3306"
        volumes:
            - ../back/db_data:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nfc-back
        networks:
            - nfc

networks:
    nfc:
        external: true
